[2025-01-27T04:22:24.024+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available manual__2025-01-27T04:22:21.652559+00:00 [queued]>
[2025-01-27T04:22:24.037+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available manual__2025-01-27T04:22:21.652559+00:00 [queued]>
[2025-01-27T04:22:24.038+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2025-01-27T04:22:24.038+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2025-01-27T04:22:24.039+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2025-01-27T04:22:24.061+0000] {taskinstance.py:1383} INFO - Executing <Task(HttpSensor): is_api_available> on 2025-01-27 04:22:21.652559+00:00
[2025-01-27T04:22:24.068+0000] {standard_task_runner.py:55} INFO - Started process 6866 to run task
[2025-01-27T04:22:24.072+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', 'manual__2025-01-27T04:22:21.652559+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpm00h5kf3']
[2025-01-27T04:22:24.075+0000] {standard_task_runner.py:83} INFO - Job 20: Subtask is_api_available
[2025-01-27T04:22:24.162+0000] {task_command.py:376} INFO - Running <TaskInstance: user_processing.is_api_available manual__2025-01-27T04:22:21.652559+00:00 [running]> on host e298d0337d0c
[2025-01-27T04:22:24.242+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2025-01-27T04:22:21.652559+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-01-27T04:22:21.652559+00:00
[2025-01-27T04:22:24.243+0000] {http.py:120} INFO - Poking: api/
[2025-01-27T04:22:24.260+0000] {base.py:71} INFO - Using connection ID 'user_api' for task execution.
[2025-01-27T04:22:24.266+0000] {http.py:148} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2025-01-27T04:22:24.522+0000] {base.py:213} INFO - Success criteria met. Exiting.
[2025-01-27T04:22:24.536+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20250127T042221, start_date=20250127T042224, end_date=20250127T042224
[2025-01-27T04:22:24.566+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2025-01-27T04:22:24.588+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
