[2025-01-27T04:15:30.017+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available manual__2025-01-27T04:15:28.076253+00:00 [queued]>
[2025-01-27T04:15:30.030+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available manual__2025-01-27T04:15:28.076253+00:00 [queued]>
[2025-01-27T04:15:30.030+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2025-01-27T04:15:30.031+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2025-01-27T04:15:30.031+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2025-01-27T04:15:30.049+0000] {taskinstance.py:1383} INFO - Executing <Task(HttpSensor): is_api_available> on 2025-01-27 04:15:28.076253+00:00
[2025-01-27T04:15:30.053+0000] {standard_task_runner.py:55} INFO - Started process 6540 to run task
[2025-01-27T04:15:30.057+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', 'manual__2025-01-27T04:15:28.076253+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpvdyuhaic']
[2025-01-27T04:15:30.058+0000] {standard_task_runner.py:83} INFO - Job 14: Subtask is_api_available
[2025-01-27T04:15:30.130+0000] {task_command.py:376} INFO - Running <TaskInstance: user_processing.is_api_available manual__2025-01-27T04:15:28.076253+00:00 [running]> on host e298d0337d0c
[2025-01-27T04:15:30.209+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2025-01-27T04:15:28.076253+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-01-27T04:15:28.076253+00:00
[2025-01-27T04:15:30.210+0000] {http.py:120} INFO - Poking: api/
[2025-01-27T04:15:30.225+0000] {base.py:71} INFO - Using connection ID 'user_api' for task execution.
[2025-01-27T04:15:30.229+0000] {http.py:148} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2025-01-27T04:15:30.470+0000] {base.py:213} INFO - Success criteria met. Exiting.
[2025-01-27T04:15:30.484+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20250127T041528, start_date=20250127T041530, end_date=20250127T041530
[2025-01-27T04:15:30.550+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2025-01-27T04:15:30.575+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
