[2025-01-27T20:17:35.643+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.store_user manual__2025-01-27T20:17:26.057579+00:00 [queued]>
[2025-01-27T20:17:35.654+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.store_user manual__2025-01-27T20:17:26.057579+00:00 [queued]>
[2025-01-27T20:17:35.654+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2025-01-27T20:17:35.655+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2025-01-27T20:17:35.656+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2025-01-27T20:17:35.672+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): store_user> on 2025-01-27 20:17:26.057579+00:00
[2025-01-27T20:17:35.677+0000] {standard_task_runner.py:55} INFO - Started process 9742 to run task
[2025-01-27T20:17:35.680+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'store_user', 'manual__2025-01-27T20:17:26.057579+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpvmt60ex0']
[2025-01-27T20:17:35.682+0000] {standard_task_runner.py:83} INFO - Job 30: Subtask store_user
[2025-01-27T20:17:35.756+0000] {task_command.py:376} INFO - Running <TaskInstance: user_processing.store_user manual__2025-01-27T20:17:26.057579+00:00 [running]> on host e298d0337d0c
[2025-01-27T20:17:35.829+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=store_user
AIRFLOW_CTX_EXECUTION_DATE=2025-01-27T20:17:26.057579+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-01-27T20:17:26.057579+00:00
[2025-01-27T20:17:35.831+0000] {postgres.py:129} INFO - Running copy expert: COPY users from stdin WITH DELIMITER as ',' , filename: /tmp/processed_user.csv
[2025-01-27T20:17:35.839+0000] {base.py:71} INFO - Using connection ID 'postgres' for task execution.
[2025-01-27T20:17:35.849+0000] {python.py:177} INFO - Done. Returned value was: None
[2025-01-27T20:17:35.859+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=store_user, execution_date=20250127T201726, start_date=20250127T201735, end_date=20250127T201735
[2025-01-27T20:17:35.892+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2025-01-27T20:17:35.914+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
