[2025-01-27T03:20:32.501+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.create_table manual__2025-01-27T03:20:30.657368+00:00 [queued]>
[2025-01-27T03:20:32.516+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.create_table manual__2025-01-27T03:20:30.657368+00:00 [queued]>
[2025-01-27T03:20:32.516+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2025-01-27T03:20:32.517+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2025-01-27T03:20:32.518+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2025-01-27T03:20:32.537+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): create_table> on 2025-01-27 03:20:30.657368+00:00
[2025-01-27T03:20:32.545+0000] {standard_task_runner.py:55} INFO - Started process 3954 to run task
[2025-01-27T03:20:32.553+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'create_table', 'manual__2025-01-27T03:20:30.657368+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpgtiswswa']
[2025-01-27T03:20:32.553+0000] {standard_task_runner.py:83} INFO - Job 13: Subtask create_table
[2025-01-27T03:20:32.654+0000] {task_command.py:376} INFO - Running <TaskInstance: user_processing.create_table manual__2025-01-27T03:20:30.657368+00:00 [running]> on host e298d0337d0c
[2025-01-27T03:20:32.779+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2025-01-27T03:20:30.657368+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-01-27T03:20:30.657368+00:00
[2025-01-27T03:20:32.794+0000] {base.py:71} INFO - Using connection ID 'postgres' for task execution.
[2025-01-27T03:20:32.801+0000] {sql.py:315} INFO - Running statement: 
        CREATE TABLE if not exists users (
            firstname TEXT NOT NULL,
            lastname TEXT NOT NULL,
            country TEXT NOT NULL,
            username TEXT NOT NULL,
            password TEXT NOT NULL,
            email TEXT NOT NULL
        );
        , parameters: None
[2025-01-27T03:20:32.803+0000] {postgres.py:96} INFO - NOTICE:  relation "users" already exists, skipping

[2025-01-27T03:20:32.814+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=create_table, execution_date=20250127T032030, start_date=20250127T032032, end_date=20250127T032032
[2025-01-27T03:20:32.845+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2025-01-27T03:20:32.869+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
