[2025-01-27T04:22:24.000+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.create_table manual__2025-01-27T04:22:21.652559+00:00 [queued]>
[2025-01-27T04:22:24.013+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.create_table manual__2025-01-27T04:22:21.652559+00:00 [queued]>
[2025-01-27T04:22:24.013+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2025-01-27T04:22:24.014+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2025-01-27T04:22:24.014+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2025-01-27T04:22:24.029+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): create_table> on 2025-01-27 04:22:21.652559+00:00
[2025-01-27T04:22:24.035+0000] {standard_task_runner.py:55} INFO - Started process 6864 to run task
[2025-01-27T04:22:24.039+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'create_table', 'manual__2025-01-27T04:22:21.652559+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpaa6fsgxw']
[2025-01-27T04:22:24.042+0000] {standard_task_runner.py:83} INFO - Job 18: Subtask create_table
[2025-01-27T04:22:24.135+0000] {task_command.py:376} INFO - Running <TaskInstance: user_processing.create_table manual__2025-01-27T04:22:21.652559+00:00 [running]> on host e298d0337d0c
[2025-01-27T04:22:24.215+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2025-01-27T04:22:21.652559+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-01-27T04:22:21.652559+00:00
[2025-01-27T04:22:24.225+0000] {base.py:71} INFO - Using connection ID 'postgres' for task execution.
[2025-01-27T04:22:24.229+0000] {sql.py:315} INFO - Running statement: 
        CREATE TABLE if not exists users (
            firstname TEXT NOT NULL,
            lastname TEXT NOT NULL,
            country TEXT NOT NULL,
            username TEXT NOT NULL,
            password TEXT NOT NULL,
            email TEXT NOT NULL
        );
        , parameters: None
[2025-01-27T04:22:24.230+0000] {postgres.py:96} INFO - NOTICE:  relation "users" already exists, skipping

[2025-01-27T04:22:24.242+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=create_table, execution_date=20250127T042221, start_date=20250127T042224, end_date=20250127T042224
[2025-01-27T04:22:24.292+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2025-01-27T04:22:24.315+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
